FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

ENV PYTHONUNBUFFERED=1
ENV PRS_CONNECTOR_CONFIG=/configs/config.json

CMD ["python", "/app/connector.py"]
